version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - "4000:4000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stratosflower_landing_site
    ports:
      - "8001:5432"